const translations = {
    es: {
        title: "Calendario de Actividades",
        btn_bulletin: "Boletín",
        btn_notif: "Activar Notificaciones",
        ph_title: "Ej. Noche de Hogar",
        ph_loc: "Ej. Capilla",
        ph_img: "URL de Flyer/Imagen",
        ph_desc: "Detalles de la actividad...",
        loginBtn: " Acceso Admin",
        logoutBtn: " Salir",
        scriptureTitle: "Escritura del Día",
        loadingScripture: "Cargando escritura...",
        weeklyViewTitle: "Vista de la Semana Seleccionada",
        noEvents: "Sin eventos",
        months: ["Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre"],
        monthsShort: ["Ene", "Feb", "Mar", "Abr", "May", "Jun", "Jul", "Ago", "Sep", "Oct", "Nov", "Dic"],
        days: ["Domingo", "Lunes", "Martes", "Miércoles", "Jueves", "Viernes", "Sábado"],
        daysShort: ["Dom", "Lun", "Mar", "Mié", "Jue", "Vie", "Sáb"],
        
        type_general: "General",
        type_youth: "Mujeres Jóvenes",
        type_youngMen: "Hombres Jóvenes",
        type_relief: "Soc. de Socorro",
        type_elders: "Élderes",
        type_primary: "Primaria",
        type_yas: "JAS",
        type_district: "Distrito",
        type_priesthood: "Sacerdocio",
        
        footer_logo: "Herramienta de Calendario para Miembros",
        footer_install: " Instalar App",
        footer_site: " Visitar Sitio Oficial",
        footer_copy: "Herramienta independiente creada para que los miembros puedan organizar sus días y actividades de forma sencilla.",
        
        modal_loginTitle: "Acceso de Administrador",
        modal_loginDesc: "Ingrese sus credenciales para administrar eventos.",
        modal_user: "Usuario",
        modal_pass: "Contraseña",
        modal_loginBtn: "Ingresar",
        modal_error: "Credenciales incorrectas",
        
        modal_addEvent: "Agregar Evento",
        modal_editEvent: "Editar Evento",
        modal_eventTitle: "Título de la Actividad",
        modal_eventTime: "Hora",
        modal_eventLoc: "Lugar",
        modal_eventDesc: "Descripción",
        modal_eventType: "Tipo",
        modal_delete: "Eliminar",
        modal_save: "Guardar Evento",
        
        modal_detailsTitle: "Detalles del Evento",
        modal_detailsEdit: " Editar Evento",
        
        modal_manageAdmins: "Líderes Autorizados",
        modal_newAccount: "Crea cuentas para que otros líderes suban eventos.",
        modal_createBtn: "Crear Cuenta de Líder",
        modal_activeAccounts: "Cuentas Activas",

        footer_directory: "Directorio de Líderes",
        footer_changeZone: "Cambiar Zona",
        cleaning_title: "Limpieza de Capilla",
        cleaning_assign: "Asignar / Editar",
        cleaning_modalTitle: "Asignar Limpieza",
        cleaning_modalDesc: "Escriba las familias asignadas para este sábado. Al guardar, se enviará una notificación.",
        cleaning_who: "¿Quién limpia esta semana?",
        cleaning_emptyNote: "Si dejas el campo vacío, el cuadro desaparecerá y no se enviará aviso.",
        cleaning_saveBtn: "Guardar y Enviar Aviso",
        cleaning_ph: "Ej: Familia Pérez y Gómez",
        forgot_btn: "¿Olvidó su contraseña?",
        forgot_desc: "Ingrese el correo electrónico o Nick para restablecer su contraseña:",
        forgot_ph: "Nick de usuario o correo",
        forgot_send: "Enviar enlace de recuperación",
        event_image: "Flyer o Imagen (Opcional)",
        event_rsvp: "Requerir confirmación de asistencia",
        rsvp_title: "Asistencia",
        rsvp_success: "¡Asistencia confirmada exitosamente!",
        rsvp_namePh: "Tu nombre o Familia",
        rsvp_countPh: "Cantidad de personas",
        rsvp_submit: "Confirmar Asistencia",
        rsvp_adminTitle: "Confirmados (Solo Admin):",
        rsvp_total: "Total Asistentes",
        share_whatsapp: "Compartir en WhatsApp",
        share_calendar: "Añadir a mi Calendario",
        filter_all: "Todos los Eventos",
        bull_title: "Reunión Sacramental",
        bull_subtitle: "Programa Dominical",
        bull_presiding: "Preside",
        bull_conducting: "Dirige",
        bull_openHymn: "Himno Inicial",
        bull_invocation: "Primera Oración",
        bull_wardBiz: "Asuntos del Barrio / Anuncios",
        bull_sacHymn: "Himno Sacramental",
        bull_speakers: "Discursantes",
        bull_closeHymn: "Himno Final",
        bull_benediction: "Última Oración",
        bull_saveBtn: "Guardar Programa",
        bull_editBtn: "Editar Programa",
        btn_howToGet: "Cómo llegar",
        dir_title: "Contacto de Líderes",
        dir_addTitle: "Agregar Líder (Admin)",
        dir_rolePh: "Llamamiento (Ej. Obispo)",
        dir_namePh: "Nombre completo",
        dir_phonePh: "Teléfono (Ej. +54911...)",
        dir_saveBtn: "Guardar Contacto",
        dir_contact: "Contactar",
        unit_welcome: "Bienvenido",
        unit_desc: "Para acceder al calendario de su unidad, ingrese el código único proporcionado por su líder.",
        unit_inputPh: "Ej: barrio-centro-123",
        unit_enterBtn: "Ingresar a mi Unidad",
        unit_leaderQ: "¿Eres líder y quieres crear un calendario para tu zona?",
        unit_registerBtn: "Registrar Nueva Zona y Presidente",
        unit_step1Desc: "Primero, elige un código único para tu zona. Luego verificaremos si está disponible.",
        unit_codePh: "Código de unidad (ej: estaca-norte-peru)",
        unit_verifyBtn: "Verificar Disponibilidad",
        unit_nickPh: "Nick de Pres. de Distrito (ej: presidente)",
        unit_emailPh: "Su correo real (para recuperación)",
        unit_passPh: "Contraseña (mín. 6 caracteres)",
        unit_submitBtn: "Registrar y Comenzar",
        unit_back: "← Volver atrás",
        role_district: "Presidente de Distrito / Estaca",
        role_bishopric: "Obispado / Presidencia de Rama",
        role_clerk: "Secretario de Barrio",
        role_rs: "Presidenta Soc. Socorro",
        role_eq: "Presidente Cuórum Élderes",
        role_yw: "Presidenta Mujeres Jóvenes",
        role_ym: "Presidente Hombres Jóvenes",
        role_pr: "Presidenta Primaria",
        role_ss: "Presidente Escuela Dominical",
        role_select: "Rol / Cargo...",
        admin_nickPh: "Nick de Usuario (ej: obispado)",
        admin_emailPh: "Correo Real del Líder (para recuperación)",
        admin_passPh: "Contraseña Inicial (Mín. 6 caracteres)",
        admin_cancelEdit: "Cancelar Edición",
        unit_districtSearch: "Busca tu Distrito o Estaca para comenzar:",
        unit_districtPh: "Ej: Lima Central",
        unit_wardSelect: "Ahora selecciona tu Barrio o Rama:",
        unit_districtSelected: "Distrito Seleccionado:",
        unit_changeDistrict: "Cambiar Distrito",
        unit_regDistrictTitle: "Nuevo Distrito",
        unit_regDistrictLabel: "Nombre del Distrito/Estaca:",
        unit_regWardLabel: "Nombre de tu Barrio/Rama inicial:",
        unit_regAdminLabel: "Datos del Presidente de Distrito:",
        unit_regSubmit: "Crear Distrito y Barrio"
    },
    en: {
        title: "Activity Calendar",
        btn_bulletin: "Bulletin",
        btn_notif: "Enable Notifications",
        ph_title: "E.g. FHE",
        ph_loc: "E.g. Chapel",
        ph_img: "Flyer/Image URL",
        ph_desc: "Activity details...",
        loginBtn: " Admin Access",
        logoutBtn: " Logout",
        scriptureTitle: "Scripture of the Day",
        loadingScripture: "Loading scripture...",
        weeklyViewTitle: "Selected Week View",
        noEvents: "No events",
        months: ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"],
        monthsShort: ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"],
        days: ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"],
        daysShort: ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"],
        
        type_general: "General",
        type_youth: "Young Women",
        type_youngMen: "Young Men",
        type_relief: "Relief Society",
        type_elders: "Elders Quorum",
        type_primary: "Primary",
        type_yas: "YSA",
        type_district: "District",
        type_priesthood: "Priesthood",
        
        footer_logo: "Member Calendar Tool",
        footer_install: " Install App",
        footer_site: " Visit Official Site",
        footer_copy: "Independent tool created for members to easily organize their days and activities.",
        
        modal_loginTitle: "Administrator Access",
        modal_loginDesc: "Enter your credentials to manage events.",
        modal_user: "Username",
        modal_pass: "Password",
        modal_loginBtn: "Login",
        modal_error: "Invalid credentials",
        
        modal_addEvent: "Add Event",
        modal_editEvent: "Edit Event",
        modal_eventTitle: "Activity Title",
        modal_eventTime: "Time",
        modal_eventLoc: "Location",
        modal_eventDesc: "Description",
        modal_eventType: "Type",
        modal_delete: "Delete",
        modal_save: "Save Event",
        
        modal_detailsTitle: "Event Details",
        modal_detailsEdit: " Edit Event",
        
        modal_manageAdmins: "Authorized Leaders",
        modal_newAccount: "Create accounts so other leaders can post events.",
        modal_createBtn: "Create Leader Account",
        modal_activeAccounts: "Active Accounts",

        footer_directory: "Leaders Directory",
        footer_changeZone: "Change Zone",
        cleaning_title: "Chapel Cleaning",
        cleaning_assign: "Assign / Edit",
        cleaning_modalTitle: "Assign Cleaning",
        cleaning_modalDesc: "Enter the families assigned for this Saturday. A notification will be sent upon saving.",
        cleaning_who: "Who cleans this week?",
        cleaning_emptyNote: "If left empty, the card will disappear and no notice will be sent.",
        cleaning_saveBtn: "Save & Send Notice",
        cleaning_ph: "E.g: Smith & Johnson Family",
        forgot_btn: "Forgot your password?",
        forgot_desc: "Enter your email or username to reset your password:",
        forgot_ph: "Username or email",
        forgot_send: "Send recovery link",
        event_image: "Flyer or Image (Optional)",
        event_rsvp: "Require attendance confirmation",
        rsvp_title: "Attendance",
        rsvp_success: "Attendance confirmed successfully!",
        rsvp_namePh: "Your name or Family",
        rsvp_countPh: "Number of people",
        rsvp_submit: "Confirm Attendance",
        rsvp_adminTitle: "Confirmed (Admin Only):",
        rsvp_total: "Total Attendees",
        share_whatsapp: "Share on WhatsApp",
        share_calendar: "Add to my Calendar",
        filter_all: "All Events",
        bull_title: "Sacrament Meeting",
        bull_subtitle: "Sunday Program",
        bull_presiding: "Presiding",
        bull_conducting: "Conducting",
        bull_openHymn: "Opening Hymn",
        bull_invocation: "Invocation",
        bull_wardBiz: "Ward Business / Announcements",
        bull_sacHymn: "Sacrament Hymn",
        bull_speakers: "Speakers",
        bull_closeHymn: "Closing Hymn",
        bull_benediction: "Benediction",
        bull_saveBtn: "Save Program",
        bull_editBtn: "Edit Program",
        btn_howToGet: "How to get there",
        dir_title: "Leaders Contact",
        dir_addTitle: "Add Leader (Admin)",
        dir_rolePh: "Calling (E.g. Bishop)",
        dir_namePh: "Full name",
        dir_phonePh: "Phone (E.g. +1555...)",
        dir_saveBtn: "Save Contact",
        dir_contact: "Contact",
        unit_welcome: "Welcome",
        unit_desc: "To access your unit's calendar, enter the unique code provided by your leader.",
        unit_inputPh: "E.g: ward-center-123",
        unit_enterBtn: "Enter my Unit",
        unit_leaderQ: "Are you a leader and want to create a calendar for your zone?",
        unit_registerBtn: "Register New Zone & President",
        unit_step1Desc: "First, choose a unique code for your zone. Then we'll verify if it's available.",
        unit_codePh: "Unit code (e.g: stake-north-usa)",
        unit_verifyBtn: "Verify Availability",
        unit_nickPh: "District Pres. nickname (e.g: president)",
        unit_emailPh: "Your real email (for recovery)",
        unit_passPh: "Password (min. 6 characters)",
        unit_submitBtn: "Register & Start",
        unit_back: "← Go back",
        role_district: "District / Stake President",
        role_bishopric: "Bishopric / Branch Presidency",
        role_clerk: "Ward Clerk",
        role_rs: "Relief Society President",
        role_eq: "Elders Quorum President",
        role_yw: "Young Women President",
        role_ym: "Young Men President",
        role_pr: "Primary President",
        role_ss: "Sunday School President",
        role_select: "Role / Calling...",
        admin_nickPh: "Username (e.g: bishopric)",
        admin_emailPh: "Leader's real email (for recovery)",
        admin_passPh: "Initial Password (Min. 6 characters)",
        admin_cancelEdit: "Cancel Edit",
        unit_districtSearch: "Search for your District or Stake to start:",
        unit_districtPh: "E.g: Salt Lake Central",
        unit_wardSelect: "Now select your Ward or Branch:",
        unit_districtSelected: "Selected District:",
        unit_changeDistrict: "Change District",
        unit_regDistrictTitle: "New District",
        unit_regDistrictLabel: "District/Stake Name:",
        unit_regWardLabel: "Your Initial Ward/Branch Name:",
        unit_regAdminLabel: "District President Details:",
        unit_regSubmit: "Create District and Ward"
    },
    pt: {
        title: "Calendário de Atividades",
        btn_bulletin: "Boletim",
        btn_notif: "Ativar Notificações",
        ph_title: "Ex. Reunião Familiar",
        ph_loc: "Ex. Capela",
        ph_img: "URL da Imagem/Flyer",
        ph_desc: "Detalhes da atividade...",
        loginBtn: " Acesso Admin",
        logoutBtn: " Sair",
        scriptureTitle: "Escritura do Dia",
        loadingScripture: "Carregando escritura...",
        weeklyViewTitle: "Visão da Semana Selecionada",
        noEvents: "Sem eventos",
        months: ["Janeiro", "Fevereiro", "Março", "Abril", "Maio", "Junho", "Julho", "Agosto", "Setembro", "Outubro", "Novembro", "Dezembro"],
        monthsShort: ["Jan", "Fev", "Mar", "Abr", "Mai", "Jun", "Jul", "Ago", "Set", "Out", "Nov", "Dez"],
        days: ["Domingo", "Segunda", "Terça", "Quarta", "Quinta", "Sexta", "Sábado"],
        daysShort: ["Dom", "Seg", "Ter", "Qua", "Qui", "Sex", "Sáb"],
        
        type_general: "Geral",
        type_youth: "Moças",
        type_youngMen: "Rapazes",
        type_relief: "Sociedade de Socorro",
        type_elders: "Quórum de Élderes",
        type_primary: "Primária",
        type_yas: "JAS",
        type_district: "Distrito",
        type_priesthood: "Sacerdócio",
        
        footer_logo: "Ferramenta de Calendário para Membros",
        footer_install: " Instalar App",
        footer_site: " Visitar Site Oficial",
        footer_copy: "Ferramenta independente criada para os membros organizarem facilmente seus dias e atividades.",
        
        modal_loginTitle: "Acesso de Administrador",
        modal_loginDesc: "Insira suas credenciais para gerenciar eventos.",
        modal_user: "Usuário",
        modal_pass: "Senha",
        modal_loginBtn: "Entrar",
        modal_error: "Credenciais incorretas",
        
        modal_addEvent: "Adicionar Evento",
        modal_editEvent: "Editar Evento",
        modal_eventTitle: "Título da Atividade",
        modal_eventTime: "Hora",
        modal_eventLoc: "Local",
        modal_eventDesc: "Descrição",
        modal_eventType: "Tipo",
        modal_delete: "Excluir",
        modal_save: "Salvar Evento",
        
        modal_detailsTitle: "Detalhes do Evento",
        modal_detailsEdit: " Editar Evento",
        
        modal_manageAdmins: "Líderes Autorizados",
        modal_newAccount: "Crie contas para que outros líderes publiquem eventos.",
        modal_createBtn: "Criar Conta de Líder",
        modal_activeAccounts: "Contas Ativas",

        footer_directory: "Diretório de Líderes",
        footer_changeZone: "Mudar Zona",
        cleaning_title: "Limpeza da Capela",
        cleaning_assign: "Atribuir / Editar",
        cleaning_modalTitle: "Atribuir Limpeza",
        cleaning_modalDesc: "Escreva as famílias designadas para este sábado. Uma notificação será enviada ao salvar.",
        cleaning_who: "Quem limpa esta semana?",
        cleaning_emptyNote: "Se deixar vazio, o cartão desaparecerá e nenhum aviso será enviado.",
        cleaning_saveBtn: "Salvar e Enviar Aviso",
        cleaning_ph: "Ex: Família Silva e Santos",
        forgot_btn: "Esqueceu sua senha?",
        forgot_desc: "Insira seu e-mail ou nome de usuário para redefinir sua senha:",
        forgot_ph: "Usuário ou e-mail",
        forgot_send: "Enviar link de recuperação",
        event_image: "Flyer ou Imagem (Opcional)",
        event_rsvp: "Exigir confirmação de presença",
        rsvp_title: "Presença",
        rsvp_success: "Presença confirmada com sucesso!",
        rsvp_namePh: "Seu nome ou Família",
        rsvp_countPh: "Número de pessoas",
        rsvp_submit: "Confirmar Presença",
        rsvp_adminTitle: "Confirmados (Somente Admin):",
        rsvp_total: "Total de Participantes",
        share_whatsapp: "Compartilhar no WhatsApp",
        share_calendar: "Adicionar ao meu Calendário",
        filter_all: "Todos os Eventos",
        bull_title: "Reunião Sacramental",
        bull_subtitle: "Programa Dominical",
        bull_presiding: "Preside",
        bull_conducting: "Dirige",
        bull_openHymn: "Hino Inicial",
        bull_invocation: "Primeira Oração",
        bull_wardBiz: "Assuntos da Ala / Anúncios",
        bull_sacHymn: "Hino Sacramental",
        bull_speakers: "Discursantes",
        bull_closeHymn: "Hino Final",
        bull_benediction: "Última Oração",
        bull_saveBtn: "Salvar Programa",
        bull_editBtn: "Editar Programa",
        btn_howToGet: "Como chegar",
        dir_title: "Contato de Líderes",
        dir_addTitle: "Adicionar Líder (Admin)",
        dir_rolePh: "Chamado (Ex. Bispo)",
        dir_namePh: "Nome completo",
        dir_phonePh: "Telefone (Ex. +5511...)",
        dir_saveBtn: "Salvar Contato",
        dir_contact: "Contatar",
        unit_welcome: "Bem-vindo",
        unit_desc: "Para acessar o calendário da sua unidade, insira o código único fornecido pelo seu líder.",
        unit_inputPh: "Ex: ala-centro-123",
        unit_enterBtn: "Entrar na minha Unidade",
        unit_leaderQ: "Você é líder e quer criar um calendário para sua zona?",
        unit_registerBtn: "Registrar Nova Zona e Presidente",
        unit_step1Desc: "Primeiro, escolha um código único para sua zona. Depois verificaremos se está disponível.",
        unit_codePh: "Código da unidade (ex: estaca-norte-brasil)",
        unit_verifyBtn: "Verificar Disponibilidade",
        unit_nickPh: "Nick do Pres. de Distrito (ex: presidente)",
        unit_emailPh: "Seu e-mail real (para recuperação)",
        unit_passPh: "Senha (mín. 6 caracteres)",
        unit_submitBtn: "Registrar e Começar",
        unit_back: "← Voltar",
        role_district: "Presidente de Distrito / Estaca",
        role_bishopric: "Bispado / Presidência de Ramo",
        role_clerk: "Secretário da Ala",
        role_rs: "Presidente da Sociedade de Socorro",
        role_eq: "Presidente do Quórum de Élderes",
        role_yw: "Presidente das Moças",
        role_ym: "Presidente dos Rapazes",
        role_pr: "Presidente da Primária",
        role_ss: "Presidente da Escola Dominical",
        role_select: "Cargo / Chamado...",
        admin_nickPh: "Nome de usuário (ex: bispado)",
        admin_emailPh: "E-mail real do líder (para recuperação)",
        admin_passPh: "Senha Inicial (Mín. 6 caracteres)",
        admin_cancelEdit: "Cancelar Edição",
        unit_districtSearch: "Busque seu Distrito ou Estaca para começar:",
        unit_districtPh: "Ex: São Paulo Central",
        unit_wardSelect: "Agora selecione sua Ala ou Ramo:",
        unit_districtSelected: "Distrito Selecionado:",
        unit_changeDistrict: "Mudar Distrito",
        unit_regDistrictTitle: "Novo Distrito",
        unit_regDistrictLabel: "Nome do Distrito/Estaca:",
        unit_regWardLabel: "Nome da sua Ala/Ramo inicial:",
        unit_regAdminLabel: "Dados do Presidente de Distrito:",
        unit_regSubmit: "Criar Distrito e Ala"
    },
    fr: {
        title: "Calendrier d'Activités",
        btn_bulletin: "Bulletin",
        btn_notif: "Activer les Notifications",
        ph_title: "Ex. Soirée Familiale",
        ph_loc: "Ex. Chapelle",
        ph_img: "URL de l'image/affiche",
        ph_desc: "Détails de l'activité...",
        loginBtn: " Accès Admin",
        logoutBtn: " Déconnexion",
        scriptureTitle: "Écriture du Jour",
        loadingScripture: "Chargement...",
        weeklyViewTitle: "Vue de la Semaine",
        noEvents: "Aucun événement",
        months: ["Janvier", "Février", "Mars", "Avril", "Mai", "Juin", "Juillet", "Août", "Septembre", "Octobre", "Novembre", "Décembre"],
        monthsShort: ["Jan", "Fév", "Mar", "Avr", "Mai", "Juin", "Juil", "Aoû", "Sep", "Oct", "Nov", "Déc"],
        days: ["Dimanche", "Lundi", "Mardi", "Mercredi", "Jeudi", "Vendredi", "Samedi"],
        daysShort: ["Dim", "Lun", "Mar", "Mer", "Jeu", "Ven", "Sam"],
        
        type_general: "Général",
        type_youth: "Jeunes Filles",
        type_youngMen: "Jeunes Gens",
        type_relief: "Société de Secours",
        type_elders: "Collège des Anciens",
        type_primary: "Primaire",
        type_yas: "JAS",
        type_district: "District",
        type_priesthood: "Prêtrise",
        
        footer_logo: "Outil de Calendrier pour les Membres",
        footer_install: " Installer l'App",
        footer_site: " Visiter le Site Officiel",
        footer_copy: "Outil indépendant créé pour que les membres puissent facilement organiser leurs journées et activités.",
        
        modal_loginTitle: "Accès Administrateur",
        modal_loginDesc: "Entrez vos identifiants pour gérer les événements.",
        modal_user: "Utilisateur",
        modal_pass: "Mot de passe",
        modal_loginBtn: "Connexion",
        modal_error: "Identifiants invalides",
        
        modal_addEvent: "Ajouter un Événement",
        modal_editEvent: "Modifier l'Événement",
        modal_eventTitle: "Titre de l'Activité",
        modal_eventTime: "Heure",
        modal_eventLoc: "Lieu",
        modal_eventDesc: "Description",
        modal_eventType: "Type",
        modal_delete: "Supprimer",
        modal_save: "Enregistrer l'Événement",
        
        modal_detailsTitle: "Détails de l'Événement",
        modal_detailsEdit: " Modifier l'Événement",
        
        modal_manageAdmins: "Dirigeants Autorisés",
        modal_newAccount: "Créez des comptes pour que d'autres dirigeants publient des événements.",
        modal_createBtn: "Créer un Compte de Dirigeant",
        modal_activeAccounts: "Comptes Actifs",

        footer_directory: "Répertoire des Dirigeants",
        footer_changeZone: "Changer de Zone",
        cleaning_title: "Nettoyage de la Chapelle",
        cleaning_assign: "Attribuer / Modifier",
        cleaning_modalTitle: "Attribuer le Nettoyage",
        cleaning_modalDesc: "Écrivez les familles assignées pour ce samedi. Une notification sera envoyée lors de la sauvegarde.",
        cleaning_who: "Qui nettoie cette semaine ?",
        cleaning_emptyNote: "Si laissé vide, la carte disparaîtra et aucun avis ne sera envoyé.",
        cleaning_saveBtn: "Sauvegarder et Envoyer l'Avis",
        cleaning_ph: "Ex : Famille Dupont et Martin",
        forgot_btn: "Mot de passe oublié ?",
        forgot_desc: "Entrez votre e-mail ou nom d'utilisateur pour réinitialiser votre mot de passe :",
        forgot_ph: "Nom d'utilisateur ou e-mail",
        forgot_send: "Envoyer le lien de récupération",
        event_image: "Affiche ou Image (Facultatif)",
        event_rsvp: "Exiger une confirmation de présence",
        rsvp_title: "Présence",
        rsvp_success: "Présence confirmée avec succès !",
        rsvp_namePh: "Votre nom ou Famille",
        rsvp_countPh: "Nombre de personnes",
        rsvp_submit: "Confirmer la Présence",
        rsvp_adminTitle: "Confirmés (Admin uniquement) :",
        rsvp_total: "Total de Participants",
        share_whatsapp: "Partager sur WhatsApp",
        share_calendar: "Ajouter à mon Calendrier",
        filter_all: "Tous les Événements",
        bull_title: "Réunion de Sainte-Cène",
        bull_subtitle: "Programme Dominical",
        bull_presiding: "Préside",
        bull_conducting: "Dirige",
        bull_openHymn: "Cantique d'Ouverture",
        bull_invocation: "Prière d'Ouverture",
        bull_wardBiz: "Affaires de la Paroisse / Annonces",
        bull_sacHymn: "Cantique de Sainte-Cène",
        bull_speakers: "Discours",
        bull_closeHymn: "Cantique de Clôture",
        bull_benediction: "Prière de Clôture",
        bull_saveBtn: "Sauvegarder le Programme",
        bull_editBtn: "Modifier le Programme",
        btn_howToGet: "S'y rendre",
        dir_title: "Annuaire des Dirigeants",
        dir_addTitle: "Ajouter un Dirigeant (Admin)",
        dir_rolePh: "Appel (Ex. Évêque)",
        dir_namePh: "Nom complet",
        dir_phonePh: "Téléphone (Ex. +33...)",
        dir_saveBtn: "Sauvegarder le Contact",
        dir_contact: "Contacter",
        unit_welcome: "Bienvenue",
        unit_desc: "Pour accéder au calendrier de votre unité, entrez le code unique fourni par votre dirigeant.",
        unit_inputPh: "Ex : paroisse-centre-123",
        unit_enterBtn: "Accéder à mon Unité",
        unit_leaderQ: "Vous êtes dirigeant et souhaitez créer un calendrier pour votre zone ?",
        unit_registerBtn: "Enregistrer une Nouvelle Zone et Président",
        unit_step1Desc: "D'abord, choisissez un code unique pour votre zone. Ensuite nous vérifierons s'il est disponible.",
        unit_codePh: "Code d'unité (ex : pieu-nord-france)",
        unit_verifyBtn: "Vérifier la Disponibilité",
        unit_nickPh: "Pseudo du Prés. de District (ex : président)",
        unit_emailPh: "Votre vrai e-mail (pour la récupération)",
        unit_passPh: "Mot de passe (min. 6 caractères)",
        unit_submitBtn: "Enregistrer et Commencer",
        unit_back: "← Retour",
        role_district: "Président de District / Pieu",
        role_bishopric: "Épiscopat / Présidence de Branche",
        role_clerk: "Secrétaire de Paroisse",
        role_rs: "Présidente de la Société de Secours",
        role_eq: "Président du Collège des Anciens",
        role_yw: "Présidente des Jeunes Filles",
        role_ym: "Président des Jeunes Gens",
        role_pr: "Présidente de la Primaire",
        role_ss: "Président de l'École du Dimanche",
        role_select: "Rôle / Appel...",
        admin_nickPh: "Nom d'utilisateur (ex : épiscopat)",
        admin_emailPh: "E-mail réel du dirigeant (pour récupération)",
        admin_passPh: "Mot de passe initial (Min. 6 caractères)",
        admin_cancelEdit: "Annuler la Modification"
    },
    it: {
        title: "Calendario delle Attività",
        btn_bulletin: "Bollettino",
        btn_notif: "Attiva Notifiche",
        ph_title: "Es. Serata Familiare",
        ph_loc: "Es. Cappella",
        ph_img: "URL Immagine/Volantino",
        ph_desc: "Dettagli dell'attività...",
        loginBtn: " Accesso Admin",
        logoutBtn: " Esci",
        scriptureTitle: "Scrittura del Giorno",
        loadingScripture: "Caricamento...",
        weeklyViewTitle: "Vista della Settimana",
        noEvents: "Nessun evento",
        months: ["Gennaio", "Febbraio", "Marzo", "Aprile", "Maggio", "Giugno", "Luglio", "Agosto", "Settembre", "Ottobre", "Novembre", "Dicembre"],
        monthsShort: ["Gen", "Feb", "Mar", "Apr", "Mag", "Giu", "Lug", "Ago", "Set", "Ott", "Nov", "Dic"],
        days: ["Domenica", "Lunedì", "Martedì", "Mercoledì", "Giovedì", "Venerdì", "Sabato"],
        daysShort: ["Dom", "Lun", "Mar", "Mer", "Gio", "Ven", "Sab"],
        
        type_general: "Generale",
        type_youth: "Giovani Donne",
        type_youngMen: "Giovani Uomini",
        type_relief: "Società di Soccorso",
        type_elders: "Quorum degli Anziani",
        type_primary: "Primaria",
        type_yas: "GAS",
        type_district: "Distretto",
        type_priesthood: "Sacerdozio",
        
        footer_logo: "Strumento di Calendario per i Membri",
        footer_install: " Installa App",
        footer_site: " Visita Sito Ufficiale",
        footer_copy: "Strumento indipendente creato per consentire ai membri di organizzare facilmente le proprie giornate e attività.",
        
        modal_loginTitle: "Accesso Amministratore",
        modal_loginDesc: "Inserisci le tue credenziali per gestire gli eventi.",
        modal_user: "Utente",
        modal_pass: "Parola d'ordine",
        modal_loginBtn: "Accedi",
        modal_error: "Credenziali non valide",
        
        modal_addEvent: "Aggiungi Evento",
        modal_editEvent: "Modifica Evento",
        modal_eventTitle: "Titolo dell'Attività",
        modal_eventTime: "Ora",
        modal_eventLoc: "Luogo",
        modal_eventDesc: "Descrizione",
        modal_eventType: "Tipo",
        modal_delete: "Elimina",
        modal_save: "Salva Evento",
        
        modal_detailsTitle: "Dettagli Evento",
        modal_detailsEdit: " Modifica Evento",
        
        modal_manageAdmins: "Dirigenti Autorizzati",
        modal_newAccount: "Crea account per consentire ad altri dirigenti di pubblicare eventi.",
        modal_createBtn: "Crea Account Dirigente",
        modal_activeAccounts: "Account Attivi",

        footer_directory: "Rubrica dei Dirigenti",
        footer_changeZone: "Cambia Zona",
        cleaning_title: "Pulizia della Cappella",
        cleaning_assign: "Assegnare / Modificare",
        cleaning_modalTitle: "Assegnare Pulizia",
        cleaning_modalDesc: "Scrivi le famiglie assegnate per questo sabato. Una notifica verrà inviata al salvataggio.",
        cleaning_who: "Chi pulisce questa settimana?",
        cleaning_emptyNote: "Se lasciato vuoto, la scheda scomparirà e nessun avviso verrà inviato.",
        cleaning_saveBtn: "Salva e Invia Avviso",
        cleaning_ph: "Es: Famiglia Rossi e Bianchi",
        forgot_btn: "Hai dimenticato la password?",
        forgot_desc: "Inserisci la tua e-mail o nome utente per reimpostare la password:",
        forgot_ph: "Nome utente o e-mail",
        forgot_send: "Invia link di recupero",
        event_image: "Volantino o Immagine (Facoltativo)",
        event_rsvp: "Richiedere conferma di partecipazione",
        rsvp_title: "Partecipazione",
        rsvp_success: "Partecipazione confermata con successo!",
        rsvp_namePh: "Il tuo nome o Famiglia",
        rsvp_countPh: "Numero di persone",
        rsvp_submit: "Conferma Partecipazione",
        rsvp_adminTitle: "Confermati (Solo Admin):",
        rsvp_total: "Totale Partecipanti",
        share_whatsapp: "Condividi su WhatsApp",
        share_calendar: "Aggiungi al mio Calendario",
        filter_all: "Tutti gli Eventi",
        bull_title: "Riunione Sacramentale",
        bull_subtitle: "Programma Domenicale",
        bull_presiding: "Presiede",
        bull_conducting: "Dirige",
        bull_openHymn: "Inno di Apertura",
        bull_invocation: "Prima Preghiera",
        bull_wardBiz: "Affari del Rione / Annunci",
        bull_sacHymn: "Inno Sacramentale",
        bull_speakers: "Discorsi",
        bull_closeHymn: "Inno di Chiusura",
        bull_benediction: "Ultima Preghiera",
        bull_saveBtn: "Salva Programma",
        bull_editBtn: "Modifica Programma",
        btn_howToGet: "Come arrivare",
        dir_title: "Elenco dei Dirigenti",
        dir_addTitle: "Aggiungi Dirigente (Admin)",
        dir_rolePh: "Chiamata (Es. Vescovo)",
        dir_namePh: "Nome completo",
        dir_phonePh: "Telefono (Es. +39...)",
        dir_saveBtn: "Salva Contatto",
        dir_contact: "Contattare",
        unit_welcome: "Benvenuto",
        unit_desc: "Per accedere al calendario della tua unità, inserisci il codice unico fornito dal tuo dirigente.",
        unit_inputPh: "Es: rione-centro-123",
        unit_enterBtn: "Accedi alla mia Unità",
        unit_leaderQ: "Sei un dirigente e vuoi creare un calendario per la tua zona?",
        unit_registerBtn: "Registra Nuova Zona e Presidente",
        unit_step1Desc: "Prima, scegli un codice unico per la tua zona. Poi verificheremo se è disponibile.",
        unit_codePh: "Codice unità (es: palo-nord-italia)",
        unit_verifyBtn: "Verifica Disponibilità",
        unit_nickPh: "Nick del Pres. di Distretto (es: presidente)",
        unit_emailPh: "La tua email reale (per il recupero)",
        unit_passPh: "Password (min. 6 caratteri)",
        unit_submitBtn: "Registra e Inizia",
        unit_back: "← Torna indietro",
        role_district: "Presidente di Distretto / Palo",
        role_bishopric: "Vescovato / Presidenza di Ramo",
        role_clerk: "Segretario di Rione",
        role_rs: "Presidentessa della Società di Soccorso",
        role_eq: "Presidente del Quorum degli Anziani",
        role_yw: "Presidentessa delle Giovani Donne",
        role_ym: "Presidente dei Giovani Uomini",
        role_pr: "Presidentessa della Primaria",
        role_ss: "Presidente della Scuola Domenicale",
        role_select: "Ruolo / Chiamata...",
        admin_nickPh: "Nome utente (es: vescovato)",
        admin_emailPh: "Email reale del dirigente (per recupero)",
        admin_passPh: "Password Iniziale (Min. 6 caratteri)",
        admin_cancelEdit: "Annulla Modifica"
    },
    de: {
        title: "Aktivitätskalender",
        btn_bulletin: "Programm",
        btn_notif: "Benachrichtigungen aktivieren",
        ph_title: "Z.B. Familienabend",
        ph_loc: "Z.B. Gemeindehaus",
        ph_img: "Bild/Flyer URL",
        ph_desc: "Aktivitätsdetails...",
        loginBtn: " Admin-Zugang",
        logoutBtn: " Abmelden",
        scriptureTitle: "Schriftstelle des Tages",
        loadingScripture: "Wird geladen...",
        weeklyViewTitle: "Wochenansicht",
        noEvents: "Keine Termine",
        months: ["Januar", "Februar", "März", "April", "Mai", "Juni", "Juli", "August", "September", "Oktober", "November", "Dezember"],
        monthsShort: ["Jan", "Feb", "Mär", "Apr", "Mai", "Jun", "Jul", "Aug", "Sep", "Okt", "Nov", "Dez"],
        days: ["Sonntag", "Montag", "Dienstag", "Mittwoch", "Donnerstag", "Freitag", "Samstag"],
        daysShort: ["So", "Mo", "Di", "Mi", "Do", "Fr", "Sa"],
        
        type_general: "Allgemein",
        type_youth: "Junge Damen",
        type_youngMen: "Junge Männer",
        type_relief: "FHV",
        type_elders: "Ältestenkollegium",
        type_primary: "PV",
        type_yas: "JAE",
        type_district: "Distrikt",
        type_priesthood: "Priestertum",
        
        footer_logo: "Kalender-Tool für Mitglieder",
        footer_install: " App Installieren",
        footer_site: " Offizielle Webseite",
        footer_copy: "Unabhängiges Tool, mit dem Mitglieder ihre Tage und Aktivitäten einfach organisieren können.",
        
        modal_loginTitle: "Administratorzugang",
        modal_loginDesc: "Geben Sie Ihre Anmeldedaten ein, um Veranstaltungen zu verwalten.",
        modal_user: "Benutzername",
        modal_pass: "Passwort",
        modal_loginBtn: "Anmelden",
        modal_error: "Ungültige Anmeldedaten",
        
        modal_addEvent: "Veranstaltung Hinzufügen",
        modal_editEvent: "Veranstaltung Bearbeiten",
        modal_eventTitle: "Titel der Aktivität",
        modal_eventTime: "Uhrzeit",
        modal_eventLoc: "Ort",
        modal_eventDesc: "Beschreibung",
        modal_eventType: "Typ",
        modal_delete: "Löschen",
        modal_save: "Veranstaltung Speichern",
        
        modal_detailsTitle: "Veranstaltungsdetails",
        modal_detailsEdit: " Veranstaltung Bearbeiten",
        
        modal_manageAdmins: "Berechtigte Führungskräfte",
        modal_newAccount: "Erstellen Sie Konten, damit andere Führungskräfte Veranstaltungen veröffentlichen können.",
        modal_createBtn: "Führungskraft-Konto Erstellen",
        modal_activeAccounts: "Aktive Konten",

        footer_directory: "Führungskräfte-Verzeichnis",
        footer_changeZone: "Zone Wechseln",
        cleaning_title: "Kapelle Reinigung",
        cleaning_assign: "Zuweisen / Bearbeiten",
        cleaning_modalTitle: "Reinigung Zuweisen",
        cleaning_modalDesc: "Tragen Sie die zugewiesenen Familien für diesen Samstag ein. Beim Speichern wird eine Benachrichtigung gesendet.",
        cleaning_who: "Wer reinigt diese Woche?",
        cleaning_emptyNote: "Wenn leer, verschwindet die Karte und es wird keine Benachrichtigung gesendet.",
        cleaning_saveBtn: "Speichern & Benachrichtigung Senden",
        cleaning_ph: "Z.B: Familie Müller und Schmidt",
        forgot_btn: "Passwort vergessen?",
        forgot_desc: "Geben Sie Ihre E-Mail oder Ihren Benutzernamen ein, um Ihr Passwort zurückzusetzen:",
        forgot_ph: "Benutzername oder E-Mail",
        forgot_send: "Wiederherstellungslink senden",
        event_image: "Flyer oder Bild (Optional)",
        event_rsvp: "Teilnahmebestätigung erforderlich",
        rsvp_title: "Teilnahme",
        rsvp_success: "Teilnahme erfolgreich bestätigt!",
        rsvp_namePh: "Ihr Name oder Familie",
        rsvp_countPh: "Anzahl der Personen",
        rsvp_submit: "Teilnahme Bestätigen",
        rsvp_adminTitle: "Bestätigt (Nur Admin):",
        rsvp_total: "Gesamtteilnehmer",
        share_whatsapp: "Auf WhatsApp Teilen",
        share_calendar: "Zu meinem Kalender Hinzufügen",
        filter_all: "Alle Veranstaltungen",
        bull_title: "Abendmahlsversammlung",
        bull_subtitle: "Sonntagsprogramm",
        bull_presiding: "Vorsitz",
        bull_conducting: "Leitung",
        bull_openHymn: "Eröffnungslied",
        bull_invocation: "Eröffnungsgebet",
        bull_wardBiz: "Gemeindeangelegenheiten / Ankündigungen",
        bull_sacHymn: "Abendmahlslied",
        bull_speakers: "Sprecher",
        bull_closeHymn: "Schlusslied",
        bull_benediction: "Schlussgebet",
        bull_saveBtn: "Programm Speichern",
        bull_editBtn: "Programm Bearbeiten",
        btn_howToGet: "Wegbeschreibung",
        dir_title: "Führungskräfte-Verzeichnis",
        dir_addTitle: "Führungskraft Hinzufügen (Admin)",
        dir_rolePh: "Berufung (Z.B. Bischof)",
        dir_namePh: "Vollständiger Name",
        dir_phonePh: "Telefon (Z.B. +49...)",
        dir_saveBtn: "Kontakt Speichern",
        dir_contact: "Kontaktieren",
        unit_welcome: "Willkommen",
        unit_desc: "Um auf den Kalender Ihrer Einheit zuzugreifen, geben Sie den von Ihrem Leiter bereitgestellten Code ein.",
        unit_inputPh: "Z.B: gemeinde-zentrum-123",
        unit_enterBtn: "Meine Einheit Betreten",
        unit_leaderQ: "Sind Sie ein Leiter und möchten einen Kalender für Ihre Zone erstellen?",
        unit_registerBtn: "Neue Zone & Präsident Registrieren",
        unit_step1Desc: "Wählen Sie zuerst einen einzigartigen Code für Ihre Zone. Dann prüfen wir die Verfügbarkeit.",
        unit_codePh: "Einheitscode (z.B: pfahl-nord-deutschland)",
        unit_verifyBtn: "Verfügbarkeit Prüfen",
        unit_nickPh: "Distriktspräs. Nickname (z.B: präsident)",
        unit_emailPh: "Ihre echte E-Mail (zur Wiederherstellung)",
        unit_passPh: "Passwort (min. 6 Zeichen)",
        unit_submitBtn: "Registrieren & Starten",
        unit_back: "← Zurück",
        role_district: "Distrikt- / Pfahlpräsident",
        role_bishopric: "Bischofschaft / Zweigpräsidentschaft",
        role_clerk: "Gemeindesekretär",
        role_rs: "FHV-Leiterin",
        role_eq: "Ältestenkollegiumspräsident",
        role_yw: "JD-Leiterin",
        role_ym: "JM-Leiter",
        role_pr: "PV-Leiterin",
        role_ss: "Sonntagsschulpräsident",
        role_select: "Rolle / Berufung...",
        admin_nickPh: "Benutzername (z.B: bischofschaft)",
        admin_emailPh: "Echte E-Mail des Leiters (zur Wiederherstellung)",
        admin_passPh: "Anfangspasswort (Min. 6 Zeichen)",
        admin_cancelEdit: "Bearbeitung Abbrechen"
    }
};
